### ISSUE TITLE
contacting you

### ISSUE THREAD

**Issue by shivamyadav37** [Rajkumrdusad/MyServer#2]
hello sir,
I want to contact  you but i can't reach out to you, even you haven't provided any e-mail ID .
I request you to please provide any contact link or Discord server
thanks

**Comment by Rajkumrdusad** [comment]
Hey Shivam i am very happy that you want to contact me and sorry delay. tell me how can i help you and don't call me sir because i am not we just friends or more..

**Comment by shivamyadav37** [comment]
i just want you to make a community for us , so that we can contact you anytime , like maybe on discord , or any other platform.
Thanks

**Comment by Rajkumrdusad** [comment]
Yes why not but i am not using discord sorry for this. any other ?

**Comment by shivamyadav37** [comment]
In this case , I will request that -you should figure out , on which platform we will build the community, so that we can easily reach you

**Comment by Rajkumrdusad** [comment]
Why you want to connect with us if you want help we ready to help you.

**Comment by shivamyadav37** [comment]
I know sir , but making a community will be easy for other users too.
Like I can't always message you on Github , for some silly doubts , that's why making a community will be really helpful , rest all upon you.

**Comment by Rajkumrdusad** [comment]
Ok but where you want to build community i am not on discord ?

**Comment by shivamyadav37** [comment]
I think Discord will be best , or maybe whatsapp??

**Comment by Rajkumrdusad** [comment]
Whatsaap is best.

**Comment by shivamyadav37** [comment]
hmm nice , so are you making the group??
if yes please add me contact no.- 7878609292

**Comment by Rajkumrdusad** [comment]
I am not making a group i will massage you soon..
