### ISSUE TITLE
br /> <b>Warning</b>:  Unknown: php_network_getaddresses: gethostbyname failed. errno=2 in <b>Unknown</b> on line <b>0</b><br /> [Tue Oct 15 07:52:25 2019] Failed to listen on 0.0.0..0:80 (reason: php_network_getaddresses: gethostbyname failed. errno=2)

### ISSUE THREAD

**Issue by Shubhendra-kushwaha** [Rajkumrdusad/MyServer#3]
br />
<b>Warning</b>:  Unknown: php_network_getaddresses: gethostbyname failed. errno=2 in <b>Unknown</b> on line <b>0</b><br />
[Tue Oct 15 07:52:25 2019] Failed to listen on 0.0.0..0:80 (reason: php_network_getaddresses: gethostbyname failed. errno=2)
![Screenshot_20191015_075308](https://user-images.githubusercontent.com/37535104/66795001-e31f9300-ef20-11e9-95ad-094c14e65f84.jpg)

**Comment by Rajkumrdusad** [comment]
Hey @Shubhendra-kushwaha may be there are some error in your document root path so please use proper path it may work if any error please inform us..

**Comment by Rajkumrdusad** [comment]
Hey @Shubhendra-kushwaha use following command :
$ myserver -s localhost 8080 ~/
It will start localhost server.
~/ is your termux home path you can change it to your any location.
Hope it will help you
